LF-Engineering/insights-connector-github

cmd/github/github.go
go.mod
go.sum

As per discussion with @fayazg 

Add issue closed, PR closed and PR merged events

---

Dockerfile
Makefile
cmd/github/github.go
go.mod
go.sum
scripts/example_run_issues.sh
scripts/example_run_pull_requests.sh
scripts/github.sh

Update to the newest schema

---

Dockerfile

- add GITHUB_CATEGORY for issues & pull requests connectors
Signed-off-by: linonymous <iamlinonymous@gmail.com>

DA-4639 & DA-4644: Add GITHUB_CATEGORY env var in the dockerfile

---

Dockerfile

Signed-off-by: Bammeke Michael <mike_bammeke@yahoo.com>

add github tokens to connector arguments

---

.gitignore
Makefile
cmd/encrypt/encrypt.go
cmd/github/github.go
scripts/encrypt_example.sh

Add scripts to allow running locally

---

cmd/github/github.go

Remove contributors duplicates - key is role:id

---

cmd/github/github.go
go.mod
go.sum

Specify a value for issue is a PR flag

---

cmd/github/github.go
go.mod
go.sum
scripts/encrypt_example.sh

Use shared dedup function

---

cmd/github/github.go

this is a fix for other places we generate repoID
Signed-off-by: Ibrahim Mbaziira <dev.code.ibra@gmail.com>

cleanup repoID generation

---

cmd/github/github.go
go.mod
go.sum

Update generating issue/PR assignee ID and PR reviewer ID

---

cmd/github/github.go

DA-4929 - dedup issue assignees, PR assignees/reviewers

---

.circleci/config.yml
.gitignore

Remove test env from pipeline

---

.circleci/config.yml
cmd/github/github.go

Handle secondary rate limit

---

Makefile
build/options.go
cmd/github/github.go

Add structured logging

---

cmd/github/github.go

Signed-off-by: Ibrahim Mbaziira <dev.code.ibra@gmail.com>

DA-4915: fix reactions comment/pullrequest id

---

cmd/github/github.go

Signed-off-by: Ibrahim Mbaziira <dev.code.ibra@gmail.com>

fix reactions pullrequest id

---

cmd/github/github.go

Use approver role for approve reviews

---

cmd/github/github.go

Add review creator to reviewers

---

cmd/github/github.go

Log set last sync as error

---

cmd/github/github.go
go.mod
go.sum

Add document caching for:
github-issue-assignee.removed
github-issue-comment.edited
github-issue-comment.deleted
github-issue-comment-reaction.removed
github-issue-reaction.removed
github-pullrequest-assignee.removed
github-pullrequest-comment.edited
github-pullrequest-comment.deleted
github-pullrequest-comment-reaction.removed
github-pullrequest-reviewer.removed

Add document caching

---

cmd/github/github.go

Enhance logging with minor fixes

---

cmd/github/github.go
go.mod
go.sum

Fixes:
- use different last sync date for issues and pull requests.
- remove duplicated pullrequest/issue assignees and comments.

Remove duplicated events data

---

.circleci/config.yml
cmd/github/github.go

Handle sync category error

---

cmd/github/github.go

Handle missing removed reviewers event

---

cmd/github/github.go

Ignore pullrequest from issue mode

---

cmd/github/github.go

Fix pullrequest merged event error

---

cmd/github/github.go

Process pullrequests as chuncks

---

cmd/github/github.go

clean up pull request start issue 

---

cmd/github/github.go
go.mod
go.sum

Add datalake files path to cache

---

cmd/github/github.go
go.mod
go.sum

Add check bot email

---

cmd/github/github.go
go.mod
go.sum

Sync with isbotidentity changes

---

cmd/github/github.go

Fix missing closed by for issues and pullrequests

---

cmd/github/github.go

Handle empty login

---

cmd/github/github.go

Disable multithreading

---

cmd/github/github.go

Handle empty syncs

---

cmd/github/github.go

Handle source empty updated at

---

cmd/github/github.go

Cache all pullrequest and issue events

---

cmd/github/github.go

Get source id from source
